---
label: Project
hide_body: false
display_field: client
fields:
- name: client
  type: text
  config:
    required: false
  label: Client
- name: year
  type: datetime
  label: Year
  description: ''
  config:
    required: false
    date_format: YYYY
    time_format: 
    display_utc: false
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: benefits
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Benefits
pages:
- exampleSite/content/project/Specsavers.md
- exampleSite/data/en/Clients/easyjet.md
- exampleSite/data/en/ONS.md
